networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - postgres
      - backend
      - frontend
    networks:
      - dev
    
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      DB_HOST: postgres
    ports:
      - "5432:5432"
    networks:
      - dev

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - dev