"""test running migrations

Revision ID: 00d27f6b9cec
Revises: 593db04d71d0
Create Date: 2024-07-12 17:07:24.448560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d27f6b9cec'
down_revision = '593db04d71d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
