"""test running migrations

Revision ID: 0ac44b94568e
Revises: 7fa0b9012b3b
Create Date: 2024-07-12 14:12:24.026478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac44b94568e'
down_revision = '7fa0b9012b3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
