"""test running migrations

Revision ID: 1423ead9adaa
Revises: 2369e0040075
Create Date: 2024-07-12 17:17:33.765335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1423ead9adaa'
down_revision = '2369e0040075'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
