"""test running migrations

Revision ID: 171779bc8256
Revises: 3e8c3043a7d4
Create Date: 2024-07-12 16:04:30.033220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171779bc8256'
down_revision = '3e8c3043a7d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
