"""test running migrations

Revision ID: 21f4ca2a2e0e
Revises: b17308c0a964
Create Date: 2024-07-12 16:59:01.920978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f4ca2a2e0e'
down_revision = 'b17308c0a964'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
