"""test running migrations

Revision ID: 2369e0040075
Revises: 5f34f585e46d
Create Date: 2024-07-12 17:17:31.055033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2369e0040075'
down_revision = '5f34f585e46d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
