"""test running migrations

Revision ID: 3a158d38b722
Revises: 21f4ca2a2e0e
Create Date: 2024-07-12 17:01:23.017242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a158d38b722'
down_revision = '21f4ca2a2e0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
