"""test running migrations

Revision ID: 3e8c3043a7d4
Revises: 96773effd20b
Create Date: 2024-07-12 16:04:23.824209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8c3043a7d4'
down_revision = '96773effd20b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
