"""test running migrations

Revision ID: 593db04d71d0
Revises: eaa4b3de278a
Create Date: 2024-07-12 17:07:01.990766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593db04d71d0'
down_revision = 'eaa4b3de278a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
