"""test running migrations

Revision ID: 5f34f585e46d
Revises: 9c1b5e429363
Create Date: 2024-07-12 17:10:29.773631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f34f585e46d'
down_revision = '9c1b5e429363'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
