"""test running migrations

Revision ID: 78323eb55789
Revises: b648990c549f
Create Date: 2024-07-12 17:08:27.300011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78323eb55789'
down_revision = 'b648990c549f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
