"""test running migrations

Revision ID: 7b28243238fb
Revises: d0c64fa33ae6
Create Date: 2024-07-12 16:58:17.389751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b28243238fb'
down_revision = 'd0c64fa33ae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
