"""test running migrations

Revision ID: 7fa0b9012b3b
Revises: 83c51a7c7af9
Create Date: 2024-07-12 14:06:29.273111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa0b9012b3b'
down_revision = '83c51a7c7af9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
