"""test running migrations

Revision ID: 83c51a7c7af9
Revises: 8a7a71fb1732
Create Date: 2024-07-12 13:46:40.644571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c51a7c7af9'
down_revision = '8a7a71fb1732'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
