"""test running migrations

Revision ID: 8a7a71fb1732
Revises: 60d220b6da0d
Create Date: 2024-07-12 13:14:58.444854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7a71fb1732'
down_revision = '60d220b6da0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
