"""test running migrations

Revision ID: 96773effd20b
Revises: cc02cd4c293d
Create Date: 2024-07-12 14:27:21.128951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96773effd20b'
down_revision = 'cc02cd4c293d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
