"""test running migrations

Revision ID: 9c1b5e429363
Revises: 78323eb55789
Create Date: 2024-07-12 17:09:34.306462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1b5e429363'
down_revision = '78323eb55789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
