"""test running migrations

Revision ID: a181f0ccabb6
Revises: 0ac44b94568e
Create Date: 2024-07-12 14:18:10.805053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a181f0ccabb6'
down_revision = '0ac44b94568e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
