"""test running migrations

Revision ID: a6768d882273
Revises: d45a5116d81c
Create Date: 2024-07-12 17:07:44.607243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6768d882273'
down_revision = 'd45a5116d81c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
