"""test running migrations

Revision ID: a899a3203812
Revises: b8c75d96f44b
Create Date: 2024-07-12 16:18:39.016613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a899a3203812'
down_revision = 'b8c75d96f44b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
