"""test running migrations

Revision ID: b17308c0a964
Revises: 7b28243238fb
Create Date: 2024-07-12 16:58:49.664652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17308c0a964'
down_revision = '7b28243238fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
