"""test running migrations

Revision ID: b648990c549f
Revises: a6768d882273
Create Date: 2024-07-12 17:08:21.565248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b648990c549f'
down_revision = 'a6768d882273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
