"""test running migrations

Revision ID: b8c75d96f44b
Revises: 171779bc8256
Create Date: 2024-07-12 16:12:22.887371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c75d96f44b'
down_revision = '171779bc8256'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
