"""test running migrations

Revision ID: cc02cd4c293d
Revises: a181f0ccabb6
Create Date: 2024-07-12 14:18:25.245782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc02cd4c293d'
down_revision = 'a181f0ccabb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
