"""test running migrations

Revision ID: d0c64fa33ae6
Revises: c6033305c922
Create Date: 2024-07-12 16:51:42.479589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c64fa33ae6'
down_revision = 'c6033305c922'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
