"""test running migrations

Revision ID: d45a5116d81c
Revises: 00d27f6b9cec
Create Date: 2024-07-12 17:07:39.743814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45a5116d81c'
down_revision = '00d27f6b9cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
