"""test running migrations

Revision ID: eaa4b3de278a
Revises: 3a158d38b722
Create Date: 2024-07-12 17:02:24.173267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa4b3de278a'
down_revision = '3a158d38b722'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
